version: '3.8'

services:
  express_backend:
    build:
      context: ./server/
    image: express_backend
    container_name: express_backend
    ports:
      - 5001:5001
    command: npm start
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    tty: true
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - .:/data/mongodb
  react_ui:
    build:
      context: ./
    ports:
      - 3001:3001
    environment:
      - API_URL=flask_backend:5005
    container_name: bxer.react-ui
    stdin_open: true
    volumes:
       - .:/usr/src/
       - .:/usr/src/node_modules
